services:
  app:
    image: ruby:latest
    restart: always
    stdin_open: true
    tty: true
    tmpfs:
      - /tmp
    working_dir: '/app'
    volumes:
      - bundle:/usr/local/bundle
      - .:/app
    environment:
      TZ: "Asia/Tokyo"
      RUBY_YJIT_ENABLE: 1
    command: 'bundle exec ruby main.rb'
volumes:
  bundle:
