accounts:
  hokkaido:
    prefecture_ja: 北海道
    csv:
      - https://www.harp.lg.jp/opendata/dataset/1369/resource/2828/patients.csv
    column: 5
    age_column: 8
    date: '%Y-%m-%dT00:00'
    encoding: 'CP932:UTF-8'
  aomori:
    prefecture_ja: 青森県
    csv:
      - https://opendata.pref.aomori.lg.jp/dataset/1531/resource/14815/02_20210827_%E9%99%BD%E6%80%A7%E6%82%A3%E8%80%85%E9%96%A2%E4%BF%82.csv
    column: 5
    age_column: 8
    date: '%Y年%-m月%-d日'
    encoding: 'Shift_JIS:UTF-8'
  nagano:
    prefecture_ja: 長野県
    csv:
      - https://www.pref.nagano.lg.jp/hoken-shippei/kenko/kenko/kansensho/joho/documents/200000_nagano_covid19_patients1.csv
    column: 5
    age_column: 8
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  toyama:
    prefecture_ja: 富山県
    csv:
      - http://opendata.pref.toyama.jp/files/covid19/20200403/toyama_patients.csv
    column: 3
    age_column: 4
    date: '%Y-%m-%d'
    encoding: 'BOM|UTF-8'
  fukui:
    prefecture_ja: 福井県
    csv:
      - https://www.pref.fukui.lg.jp/doc/toukei-jouhou/covid-19_d/fil/covid19_patients.csv
    column: 5
    age_column: 8
    date: '%Y/%-m/%-d'
    encoding: 'BOM|UTF-8'
  yamagata:
    prefecture_ja: 山形県
    csv:
      - https://www.pref.yamagata.jp/documents/10045/060003_yamagata_covid19_patients_0826.csv
    column: 4
    age_column: 7
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  gunma:
    prefecture_ja: 群馬県
    csv:
      - http://stopcovid19.pref.gunma.jp/csv/01kanja.csv
    column: 2
    age_column: 5
    date: '%Y年%-m月%-d日'
    encoding: 'BOM|UTF-8'
  saitama:
    prefecture_ja: 埼玉県
    csv:
      - https://opendata.pref.saitama.lg.jp/data/dataset/c3a8db28-b943-4fcc-82ec-b7febd460bec/resource/434f2904-10af-4d72-9769-0aa4be6b3a84/download/jokyo20210531.csv
    column: 2
    age_column: 3
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  tokyo:
    prefecture_ja: 東京都
    csv:
      - https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients_2020.csv
      - https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients_2021.csv
      - https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients_2022.csv
      - https://stopcovid19.metro.tokyo.lg.jp/data/130001_tokyo_covid19_patients_2022-1.csv
    column: 5
    age_column: 9
    date: '%Y-%m-%d'
    encoding: 'BOM|UTF-8'
  kanagawa:
    prefecture_ja: 神奈川県
    csv:
      - https://www.pref.kanagawa.jp/osirase/1369/data/csv/patient.csv
    column: 1
    age_column: 3
    date: '%Y-%m-%d'
    encoding: 'Shift_JIS:UTF-8'
  ishikawa:
    prefecture_ja: 石川県
    csv:
      - https://www.pref.ishikawa.lg.jp/kansen/documents/170003_ishikawa_covid19_patients.csv
    column: 5
    age_column: 7
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  mie:
    prefecture_ja: 三重県
    csv:
      - https://www.pref.mie.lg.jp/common/content/000896797.csv
    column: 5
    age_column: 8
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  gifu:
    prefecture_ja: 岐阜県
    csv:
      - https://gifu-opendata.pref.gifu.lg.jp/dataset/4661bf9d-6f75-43fb-9d59-f02eb84bb6e3/resource/9c35ee55-a140-4cd8-a266-a74edf60aa80/download/210005_gifu_covid19_patients.csv
    column: 5
    age_column: 8
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  shizuoka:
    prefecture_ja: 静岡県
    csv:
      - https://opendata.pref.shizuoka.jp/dataset/8167/resource/46279/220001_shizuoka_covid19_patients.csv
    column: 5
    age_column: 8
    date: '%Y-%-m-%-d'
    encoding: 'Shift_JIS:UTF-8'
  yamaguchi:
    prefecture_ja: 山口県
    csv:
      - https://yamaguchi-opendata.jp/ckan/dataset/f6e5cff9-ae43-4cd9-a398-085187277edf/resource/f56e6552-4c5d-4ec6-91c0-090f553e0aea/download/350001_yamaguchi_covid19_patients.csv
    column: 5
    age_column: 7
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  tokushima:
    prefecture_ja: 徳島県
    csv:
      - https://ouropendata.jp/dataset/2192/resource/6170/%E9%99%BD%E6%80%A7%E6%82%A3%E8%80%85%E5%B1%9E%E6%80%A7.csv
    column: 4
    age_column: 7
    date: '%Y-%m-%d'
    encoding: 'BOM|UTF-8'
  okayama:
    prefecture_ja: 岡山県
    csv:
      - http://www.okayama-opendata.jp/ckan/dataset/e6b3c1d2-2f1f-4735-b36e-e45d36d94761/resource/d021c012-297e-4ea9-bffa-cf55741884d1/download/kansenshashousaijouhou.csv
    column: 4
    age_column: 7
    date: '%-m月%-d日' # Year is not existed so this will not work after 2021.
    encoding: 'Shift_JIS:UTF-8'
  ehime:
    prefecture_ja: 愛媛県
    csv:
      - https://www.pref.ehime.jp/opendata-catalog/dataset/2174/resource/7073/380008_ehime_covid19_patients.csv
    column: 5
    age_column: 9
    date: '%Y-%m-%d'
    encoding: 'BOM|UTF-8'
  kochi:
    prefecture_ja: 高知県
    csv:
      - https://www.pref.kochi.lg.jp/soshiki/111301/files/2020041300141/390003_kochi_covid19_patients.csv
    column: 5
    age_column: 9
    date: '%Y/%-m/%-d'
    encoding: 'Shift_JIS:UTF-8'
  fukuoka:
    prefecture_ja: 福岡県
    csv:
      - https://ckan.open-governmentdata.org/dataset/8a9688c2-7b9f-4347-ad6e-de3b339ef740/resource/c27769a2-8634-47aa-9714-7e21c4038dd4/download/400009_pref_fukuoka_covid19_patients.csv
    column: 5
    age_column: 9
    date: '%Y/%m/%d'
    encoding: 'BOM|UTF-8'
  kumamoto:
    prefecture_ja: 熊本県
    csv:
      - "https://www.pref.kumamoto.jp/uploaded/attachment/137412.csv"
    column: 5
    age_column: 8
    date: '%Y-%m-%d'
    encoding: 'BOM|UTF-8'
  oita:
    prefecture_ja: 大分県
    csv:
      - "http://data.bodik.jp/dataset/f632f467-716c-46aa-8838-0d535f98b291/resource/3714d264-70f3-4518-a57a-8391e0851d7d/download/440001oitacovid19patients.csv"
    column: 5
    age_column: 9
    date: '%Y/%-m/%-d'
    encoding: 'BOM|UTF-8'
  nagasaki:
    prefecture_ja: 長崎県
    csv:
      - "http://data.bodik.jp/dataset/09951e04-dc5d-42e9-9a49-37443be6787e/resource/de7ce61e-1849-47a1-b758-bca3f809cdf8/download/20200716prefnagasakicovidpatients.csv"
    column: 5
    age_column: 9
    date: '%Y-%-m-%-d'
    encoding: 'BOM|UTF-8'

